DOCTOR_SEEDS = [
    {
        "name": "Dr. Priya Sharma",
        "email": "priya@telemed.ai",
        "specialization": "General Physician",
        "qualification": "MBBS, MD",
        "experience": "12 years",
        "timeslots": "09:00,09:30,10:00,10:30,11:00,11:30",
    },
    {
        "name": "Dr. Arjun Mehta",
        "email": "arjun@telemed.ai",
        "specialization": "Cardiologist",
        "qualification": "MBBS, MD, DM",
        "experience": "15 years",
        "timeslots": "10:00,10:30,11:00,11:30,12:00,12:30",
    },
    {
        "name": "Dr. Neha Gupta",
        "email": "neha@telemed.ai",
        "specialization": "Dermatologist",
        "qualification": "MBBS, MD",
        "experience": "8 years",
        "timeslots": "13:00,13:30,14:00,14:30,15:00,15:30",
    },
    {
        "name": "Dr. Rohit Verma",
        "email": "rohit@telemed.ai",
        "specialization": "Neurologist",
        "qualification": "MBBS, MD, DM",
        "experience": "18 years",
        "timeslots": "16:00,16:30,17:00,17:30,18:00,18:30",
    },
    {
        "name": "Dr. Ananya Mishra",
        "email": "ananya@telemed.ai",
        "specialization": "Pediatrician",
        "qualification": "MBBS, DCH, MD",
        "experience": "8 years",
        "timeslots": "08:00,08:30,09:00,09:30,10:00,10:30",
    },
    {
        "name": "Dr. Vikram Singh",
        "email": "vikram@telemed.ai",
        "specialization": "Orthopedic Surgeon",
        "qualification": "MBBS, MS",
        "experience": "14 years",
        "timeslots": "11:00,11:30,12:00,12:30,13:00,13:30",
    },
    {
        "name": "Dr. Anjali Krishnan",
        "email": "anjali@telemed.ai",
        "specialization": "Gynecologist",
        "qualification": "MBBS, MS",
        "experience": "11 years",
        "timeslots": "14:00,14:30,15:00,15:30,16:00,16:30",
    },
    {
        "name": "Dr. Meera Pillai",
        "email": "meera@telemed.ai",
        "specialization": "ENT Specialist",
        "qualification": "MBBS, MS",
        "experience": "9 years",
        "timeslots": "09:00,09:30,10:00,10:30,11:00,11:30",
    },
    {
        "name": "Dr. Aakash Joshi",
        "email": "aakash@telemed.ai",
        "specialization": "Pulmonologist",
        "qualification": "MBBS, MD, DM",
        "experience": "13 years",
        "timeslots": "12:00,12:30,13:00,13:30,14:00,14:30",
    },
    {
        "name": "Dr. Kavita Nair",
        "email": "kavita@telemed.ai",
        "specialization": "Endocrinologist",
        "qualification": "MBBS, MD, DM",
        "experience": "12 years",
        "timeslots": "15:00,15:30,16:00,16:30,17:00,17:30",
    },
    {
        "name": "Dr. Rahul Gupta",
        "email": "rahul@telemed.ai",
        "specialization": "Ophthalmologist",
        "qualification": "MBBS, DO, DNB",
        "experience": "14 years",
        "timeslots": "10:00,10:30,11:00,11:30,12:00,12:30",
    },
    {
        "name": "Dr. Ritu Agarwal",
        "email": "ritu@telemed.ai",
        "specialization": "Oncologist",
        "qualification": "MBBS, MD, DM",
        "experience": "13 years",
        "timeslots": "17:00,17:30,18:00,18:30,19:00,19:30",
    },
]
